const config = {
    chains:[
        {
            name:"SOL",
            id:"SOL",
            img:"/img/chains/sol.png"
        },
        {
            name:"TON",
            id:"TON",
            img:"/img/chains/ton.png"
        },
        {
            name:"ETH",
            id:"ETH",
            img:"/img/chains/eth.png"
        },
        {
            name:"BTC",
            id:"BTC",
            img:"/img/chains/btc.png"
        },
        {
            name:"LTC",
            id:"LTC",
            img:"/img/chains/ltc.png"
        },
        {
            name:"BCH",
            id:"BCH",
            img:"/img/chains/bch.png"
        },
        {
            name:"ARB",
            id:"ARB",
            img:"/img/chains/arb.png"
        },
        {
            name:"BNB",
            id:"BNB",
            img:"/img/chains/bnb.png"
        },
        {
            name:"TRX",
            id:"TRX",
            img:"/img/chains/trx.png"
        },
        {
            name:"XMR",
            id:"XMR",
            img:"/img/chains/xmr.png"
        },
        {
            name:"AVAX",
            id:"AVAX",
            img:"/img/chains/avax.png"
        },
        {
            name:"BSC-USDT",
            id:"USDTBSC",
            img:"/img/chains/usdt.png"
        },
        {
            name:"ETH-DAI",
            id:"DAIETH",
            img:"/img/chains/dai.png"
        },
    ]
}

export {
    config
}